---
- name: ensure rabbitmq bin path to sbin is properly symlinked
  shell: ln -s /usr/lib/rabbitmq/bin /usr/lib/rabbitmq/sbin creates=/usr/lib/rabbitmq/sbin

- name: ensure rabbitmq management console is enabled
  rabbitmq_plugin:
    names={{ item.name }}
    state=enabled
    prefix=/usr/lib/rabbitmq
  with_items: "{{ rabbitmq_plugins }}"
  notify:
    - restart rabbitmq-server

- name: ensure rabbitmq-server starts on a fresh reboot
  service:
    name=rabbitmq-server
    enabled=yes
    state=started
